name: Android CI

on:
  push:
    branches: [ main, develop, release ]
  pull_request:
    branches: [ main, develop, release ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Run lint
      run: ./gradlew lint
      
    - name: Upload lint results
      uses: actions/upload-artifact@v3
      with:
        name: lint-results
        path: app/build/reports/lint-results-debug.html
      
    - name: Run tests
      run: ./gradlew test
      
    - name: Build with Gradle
      run: ./gradlew build

    # disable CD temporarily
    # - name: Upload APK
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: app-debug.apk
    #     path: app/build/outputs/apk/debug/app-debug.apk

  check:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check build status
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "Build, tests, and lint passed successfully!"
          exit 0
        else
          echo "Build, tests, or lint failed. Please fix the issues before merging."
          exit 1
        fi
